# SPDX-FileCopyrightText: Â© 2022 Alexandros Theodotou <alex at zrythm dot org>
# SPDX-License-Identifier: FSFAP
name: MacOS
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: zrythm
      - name: Install dependencies
        run: |
          pwd
          set -e
          echo "updating brew"
          brew update || true
          echo "installing deps"
          # use || true because it returns 1
          brew install  gnu-sed fftw meson libsamplerate sdl2 chromaprint libgtop lilv librsvg adwaita-icon-theme guile gtksourceview5 graphviz zstd npm rt-audio rtmidi jack qjackctl cmake help2man xxhash vamp-plugin-sdk json-glib glib-utils libsass sassc carla faust boost malleefoul/zrythm-reqs/libaudec malleefoul/zrythm-reqs/libbacktrace malleefoul/zrythm-reqs/zix malleefoul/zrythm-reqs/appstream malleefoul/zrythm-reqs/libcyaml malleefoul/zrythm-reqs/libpanel-detach malleefou/versions/libadwaita@1.4 malleefou/versions/gtk4@4.13.0 || true
          echo "linking python"
          brew link --overwrite python
          #npm install -g appdmg
          echo "installing cmake"
          pip3 install scikit-build
          pip3 install cmake
      - name: Fetch repos and files
        run: |
          git clone https://github.com/mesonbuild/meson
      - name: Build
        run: |
          cd zrythm
          mv VERSION VERSION.txt
          gsed -i "s|'VERSION'|'VERSION.txt'|" meson.build
          meson build -Dtests=true -Dgtk4:x11-backend=false -Dx11=disabled
          ninja -C build

      - name: Test
        run: |
          cd zrythm
          meson test -C build || cat build/meson-logs/testlog.txt

      - name: Install
        run: |
          cd zrythm
          ninja -C build install

