# SPDX-FileCopyrightText: Â© 2021 Alexandros Theodotou <alex at zrythm dot org>
# SPDX-License-Identifier: FSFAP
name: MSYS2 UCRT64
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          path: zrythm
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            zip
            unzip
            base-devel
            tree
            guile
            libguile-devel
            mingw-w64-i686-toolchain
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-libsamplerate
            mingw-w64-ucrt-x86_64-fftw
            mingw-w64-ucrt-x86_64-ffmpeg
            mingw-w64-ucrt-x86_64-libyaml
            mingw-w64-ucrt-x86_64-libsndfile
            mingw-w64-ucrt-x86_64-rubberband
            mingw-w64-ucrt-x86_64-boost
            mingw-w64-ucrt-x86_64-dlfcn
            mingw-w64-ucrt-x86_64-SDL2
            mingw-w64-ucrt-x86_64-chromaprint
            mingw-w64-ucrt-x86_64-graphviz
            mingw-w64-ucrt-x86_64-cantarell-fonts
            mingw-w64-ucrt-x86_64-gtksourceview5
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-binutils
            mingw-w64-ucrt-x86_64-portaudio
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-python-setuptools
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-python-pip
            mingw-w64-ucrt-x86_64-libadwaita
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-python3
            mingw-w64-ucrt-x86_64-gtk-doc
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-adwaita-icon-theme
            mingw-w64-ucrt-x86_64-curl-winssl
            mingw-w64-ucrt-x86_64-pcre2
            mingw-w64-ucrt-x86_64-xxhash
            mingw-w64-ucrt-x86_64-vamp-plugin-sdk
            mingw-w64-ucrt-x86_64-json-glib
            mingw-w64-ucrt-x86_64-iconv
            mingw-w64-ucrt-x86_64-graphene
            mingw-w64-ucrt-x86_64-libsass
            mingw-w64-ucrt-x86_64-sassc
      - name: Fetch repos and files
        run: |
          mkdir /c/src
          MSYS=winsymlinks:native mv zrythm /c/src/
          cd /c/src
          pwd
          git clone https://git.sr.ht/~alextee/zrythm-builds
          git clone https://git.sr.ht/~alextee/zrythm-installer
      - name: Install deps
        run: |
          cd /c/src/zrythm-installer
          meson build -Ddistro=windows10-msys
          ninja -C build run-mingw-lilv mingw-carla-ucrt64-build mingw-carla-mingw32-build
      - name: Replace non-ASCII chars in TRANSLATORS
        run: |
          cd /c/src/zrythm
          iconv -c -f utf-8 -t ascii//TRANSLIT TRANSLATORS > TRANSLATORS2 || true
          rm TRANSLATORS
          mv TRANSLATORS2 TRANSLATORS
          sed -i -e 's|"|'\''|g' TRANSLATORS
      - name: Build and test
        run: |
          cd /c/src/zrythm
          sed -i -e "s|'-lssp'|'-Wl,-allow-multiple-definition'|g" meson.build
          meson build -Dtests=true -Dcarla_binaries_dir_32bit=D:/a/_temp/msys64/mingw32/lib/carla -Db_lto=false -Dmanpage=false
          ninja -C build
          meson test -C build
          meson install -C build
